pipeline:
  name: raq-pipeline
  identifier: raqpipeline
  projectIdentifier: mphasis
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: raq-stage
        identifier: raqstage
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: CreateStack
                  name: raq-stack
                  identifier: raqstack
                  spec:
                    provisionerIdentifier: AWS
                    configuration:
                      stackName: raq-satck
                      connectorRef: org.ecsconnector
                      region: us-east-1
                      templateFile:
                        type: Remote
                        spec:
                          store:
                            type: Github
                            spec:
                              paths:
                                - vpc.yaml
                              connectorRef: Pomconnector
                              gitFetchType: Branch
                              branch: main
                      roleArn: ""
                  timeout: 10m
        tags: {}
