AWSTemplateFormatVersion: "2010-09-09"
Description: "Test Instance"
Parameters:
  InstanceTypeParameter:
    Type: String
    Default: t2.micro
  InstanceImageId:
    Type: String
    Default: ami-0bb84b8ffd87024d8
  InstanceKeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Default: microkube
Resources:
  Ec2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceTypeParameter
      ImageId: !Ref InstanceImageId
      AvailabilityZone: us-east-1b
      KeyName: !Ref InstanceKeyName
      Tags:
        - Key: User
          Value: khaja.uddin
      SubnetId: subnet-020223ed44088a828 
