AWSTemplateFormatVersion: "2010-09-09"
Description: "This is Secret"
Parameters:
  HarnessSecretName:
    Type: String
    Description: Name for the AWS Secret
  AWSSecretName:
    Type: String
    Description: Name for the AWS Secret
Resources: 
  MySecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Ref AWSSecretName
      Description: This is Demo-secret
      SecretString: !Ref HarnessSecretName

