Parameters:
  HarnessSecretName:
    Type: String
    Description: Name for the AWS Secret
  AWSSecretName:
    Type: String
    Description: Name for the AWS Secret
    Type: AWS::SecretsManager::Secret
MySecret:
    Properties:
      Name: ! Ref AWSSecretName
      Description: !Ref SecretDescription
      SecretString: !Ref HarnessSecretName

