AWSTemplateFormatVersion: "2010-09-09"
Description: "VPC
Resources:
  Vpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.8/16
      Tags:
        - Key: User
          Value: khaja.uddin
